export const SERVICES = [
  "Home",
  "Used Auto Parts",
  "Used Transmissions",
  "Used Engines",
];

export const YEAR = [
  "Year",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
];

export const ENGINE_SIZES = [
  "Engine Size",
  "1.5L",
  "1.6L",
  "1.7L",
  "1.8L",
  "1.9L",
  "2.0L",
  "2.1L",
  "2.2L",
  "2.3L",
  "2.4L",
  "2.5L",
  "2.6L",
  "2.7L",
  "2.8L",
  "2.9L",
  "3.0L",
  "3.1L",
  "3.2L",
  "3.3L",
  "3.4L",
  "3.5L",
  "3.6L",
  "3.7L",
  "3.8L",
  "3.9L",
  "4.0L",
  "4.1L",
  "4.2L",
  "4.3L",
  "4.4L",
  "4.5L",
  "4.6L",
  "4.7L",
  "4.8L",
  "4.9L",
  "5.0L",
  "5.1L",
  "5.2L",
  "5.3L",
  "5.4L",
  "5.5L",
  "5.6L",
  "5.7L",
  "5.8L",
  "5.9L",
  "6.0L",
  "6.1L",
  "6.2L",
  "6.3L",
  "6.4L",
  "6.5L",
  "6.6L",
  "6.7L",
  "6.8L",
  "6.9L",
  "7.0L",
  "7.1L",
  "7.2L",
  "7.3L",
  "7.4L",
  "7.5L",
  "7.6L",
  "7.7L",
  "7.8L",
  "7.9L",
  "8.0L",
  "8.1L",
  "8.2L",
  "8.3L",
  "8.4L",
  "8.5L",
  "8.6L",
  "8.7L",
  "8.8L",
  "8.9L",
  "9.0L",
  "9.1L",
  "9.2L",
  "9.3L",
  "9.4L",
  "9.5L",
  "9.6L",
  "9.7L",
  "9.8L",
  "9.9L",
  "10.0",
];

interface MakeType {
  [key: string]: string[];
}

export const MAKE: MakeType = {
  "Choose Your Car": ["Choose Model"],
  Acura: [
    "Choose Model",
    "CL",
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX",
  ],
  "Aston Martin": ["Choose Model", "Aston Martin"],
  Audi: [
    "Choose Model",
    "100",
    "200",
    "4000 2 &amp; 4 Door Sedan",
    "4000 Quattro",
    "5000 &amp; 5000 Quattro",
    "80 Series",
    "90 Series",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "AllRoad",
    "Cabriolet",
    "Coupe GT",
    "Coupe Quattro",
    "Fox",
    "Q3",
    "Q5",
    "Q7",
    "R8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "Sport Coupe",
    "Super 90",
    "TT",
    "V8 Quattro",
  ],
  Bentley: ["Choose Model", "Bentley"],
  BMW: [
    "Choose Model",
    "1M",
    "128i",
    "135i",
    "1602",
    "1800",
    "228i",
    "230i",
    "2002",
    "2500",
    "2800",
    "3",
    "318i",
    "320i",
    "323i",
    "325e",
    "325i",
    "328i",
    "328i GT",
    "330e",
    "330i",
    "330i GT",
    "335i",
    "335i GT",
    "340i",
    "340i GT",
    "428i",
    "430i",
    "435i",
    "440i",
    "524TD",
    "525i",
    "528e",
    "528i",
    "530e",
    "530i",
    "533i",
    "535i",
    "535i GT",
    "540i",
    "545i",
    "550i",
    "550i GT",
    "630CSi",
    "633CSi",
    "635CSi",
    "640i",
    "640i GT",
    "645Ci",
    "650i",
    "728",
    "732",
    "733i",
    "735i",
    "740e",
    "740i",
    "745i",
    "750i",
    "760i",
    "840i",
    "850i",
    "ActiveE",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "Alpina B6",
    "Alpina B7",
    "I3",
    "I8",
    "L6",
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M235i",
    "M240i",
    "M550i",
    "M760i",
    "X1",
    "X3",
    "X4",
    "X5",
    "X5M",
    "X6",
    "X6M",
    "Z3",
    "Z4",
    "Z8",
    "Other",
  ],
  Buick: [
    "Choose Model",
    "Allure",
    "Apollo",
    "Cascada",
    "Century",
    "Electra (1979 Down)",
    "Electra (1980 Up)",
    "Enclave",
    "Encore",
    "Envision",
    "Lacrosse",
    "LeSabre (1979 Down)",
    "LeSabre (1980 Up)",
    "Limited",
    "Lucerne",
    "Park Ave (1979 Down)",
    "Park Ave (1980 Up)",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal Somerset (1984 Down)",
    "Rendezvous",
    "Riviera",
    "Roadmaster (1979 Down)",
    "Roadmaster (1980 Up)",
    "Skyhawk",
    "Skylark",
    "Somerset (1985 Up)",
    "Special",
    "Terraza",
    "Verano",
    "Other",
  ],
  Cadillac: [
    "Choose Model",
    "Allante",
    "ATS",
    "Brougham",
    "CT6",
    "CTS",
    "Catera",
    "Cimarron",
    "Concours",
    "DeVille (1979 Down)",
    "DeVille (1980 Up)",
    "DHS",
    "DTS (2005 Down)",
    "DTS (2006 Up)",
    "ELR",
    "Eldorado (1966 Down)",
    "Eldorado (1967 Up)",
    "Escalade",
    "Escalade-ESV",
    "Escalade-EXT",
    "Fleetwood (1979 Down)",
    "Fleetwood (1980 Up)",
    "Seville (incl STS)",
    "SRX",
    "STS",
    "XLR",
    "XT5",
    "XTS",
    "Other",
  ],
  Chevy: [
    "Choose Model",
    "Astra",
    "Aveo",
    "Beretta",
    "Blazer, Full Size",
    "Blazer, S10/S15",
    "Bolt",
    "C2",
    "Camaro",
    "Caprice (1979 Down)",
    "Caprice (1980 Up)",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "Chevelle",
    "Chevette",
    "Pickup FWD (Non US Mkt)",
    "Small Car (Non US Mkt)",
    "Citation",
    "City Express",
    "Cobalt",
    "Corsa",
    "Corsica",
    "Corvair",
    "Corvette",
    "Cruze",
    "El Camino (1963 Down)",
    "El Camino (1964-1977)",
    "El Camino (1978 Up)",
    "Epica",
    "Equinox",
    "HHR",
    "Impala (1979 Down)",
    "Impala (1980 Up)",
    "Lumina Car",
    "Lumina Van",
    "Luv (See Also Isuzu Mini P-Up)",
    "Malibu",
    "Meriva",
    "Metro",
    "Monte Carlo",
    "Monza",
    "Nova &amp; II (1967 Down)",
    "Nova (1968 Up)",
    "Optra",
    "Orlando",
    "Prizm",
    "S/10/S15/Sonoma",
    "Sonic",
    "Spark",
    "Spectrum",
    "Sprint",
    "SS",
    "SSR",
    "Suburban-10 (1988 Down)",
    "Suburban-20 (1988 Down)",
    "Suburban-30 (1966 Down)",
    "Suburban-1000 (1963-1966)",
    "Suburban-1500",
    "Suburban-2500 (1967 Up)",
    "Suburban-3500",
    "Tahoe",
    "Tigra",
    "Tornado",
    "Tracker",
    "TrailBlazer",
    "TrailBlazer-EXT",
    "Traverse",
    "Trax",
    "Truck-10 Series (1987 Down)",
    "Truck-20 Series (1988 Down)",
    "Truck-30 Series (1988 Down)",
    "Truck-1500 Series (1988-1999)",
    "Truck-2500 Series (1988-2000)",
    "Truck-3500 Series (1988-2001)",
    "Truck-Avalanche 1500",
    "Truck-Avalanche 2500",
    "Truck-C3100",
    "Truck-C3600",
    "Truck-C3800",
    "Truck-Colorado",
    "Truck-Forward Control",
    "Truck-Kodiak",
    "Truck-Luv Mini Pup",
    "Truck-S10/S15/Sonoma",
    "Truck-Silverado 1500 (1999 Up)",
    "Truck-Silverado 2500 (1999 Up)",
    "Truck-Silverado 3500 (2001 Up)",
    "Truck-Tilt Cab",
    "Uplander",
    "Van 10",
    "Van 20",
    "Van 30",
    "Van Express 1500",
    "Van Express 2500",
    "Van Express 3500",
    "Vectra",
    "Vega",
    "Venture",
    "Volt",
    "Zafira",
    "Other",
  ],
  Chrysler: [
    "Choose Model",
    "200",
    "300",
    "300M",
    "Aspen",
    "Atos",
    "Attitude",
    "Cirrus",
    "Concorde",
    "Conquest",
    "Cordoba",
    "Crossfire",
    "E Class",
    "Fifth Avenue - FWD",
    "Fifth Avenue - RWD (1979 Up)",
    "Imperial",
    "LHS",
    "Laser",
    "Lebaron",
    "New Yorker - FWD",
    "New Yorker - RWD",
    "Newport",
    "Pacifica",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC",
    "Town and Country",
    "Voyager",
    "Other",
  ],
  Dodge: [
    "Choose Model",
    "400",
    "600",
    "Aries",
    "Aspen",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger (Chrysler)",
    "Challenger (Mitsubishi)",
    "Charger",
    "Colt-not Vista",
    "Colt Vista",
    "Cricket",
    "D50/Ram 50 (See also Plymouth Arrow Truck)",
    "Dakota",
    "Dart",
    "Daytona",
    "Diplomat",
    "Durango",
    "Dynasty",
    "Intrepid",
    "Journey",
    "Lancer",
    "Magnum",
    "Mirada",
    "Monaco (1978 Down)",
    "Monaco (1990 Up)",
    "Neon",
    "Nitro",
    "Omni",
    "Promaster 1500",
    "Promaster 2500",
    "Promaster 3500",
    "Raider",
    "Ramcharger",
    "Rampage",
    "Shadow",
    "Spirit",
    "St Regis",
    "Stealth",
    "Stratus",
    "Truck-100 Series (1989 Down)",
    "Truck-200 Series (1980 Down)",
    "Truck-300 Series (1980 Down)",
    "Truck-400 Series",
    "Truck-150 (1978-1993)",
    "Truck-250 Series (1981-1993)",
    "Truck-350 Series (1981-1993)",
    "Truck-450 Series",
    "Truck-1500 (1994 Up)",
    "Truck-2500 Series (1994 Up)",
    "Truck-3500 (1994 Up)",
    "Truck-4500 Series",
    "Truck-5500 Series",
    "Truck-D50/Ram 50",
    "Truck-Dakota",
    "Truck-Forward Control",
    "Truck-Rampage",
    "Van 100",
    "Van 150",
    "Van 200",
    "Van 250",
    "Van 300",
    "Van 350",
    "Van 1500",
    "Van 2500",
    "Van 3500",
    "Van (Promaster City)",
    "Van (Sprinter 2500)",
    "Van (Sprinter 3500)",
    "Verna",
    "Viper",
    "Other",
  ],
  Eagle: [
    "Choose Model",
    "2000 GTX",
    "2000 GTX",
    "Premier",
    "Summit",
    "Talon",
    "Vision",
  ],
  Ferrari: ["Choose Model", "Ferrari"],
  Ford: [
    "Choose Model",
    "500",
    "Aerostar",
    "Aspire",
    "Bronco (Full Size)",
    "Bronco II",
    "C-Max",
    "Contour",
    "Cortina",
    "Courier",
    "Crown Vic (1982 Down)",
    "Crown Vic (1983 Up)",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "EXP",
    "Expedition",
    "Explorer",
    "Fairlane",
    "Fairmont",
    "Falcon",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus RS",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Galaxie",
    "Granada",
    "GT",
    "Ikon",
    "KA",
    "LTD (1978 Down)",
    "LTD (1979 Up)",
    "LTD II",
    "Maverick",
    "Mondeo",
    "Mustang",
    "Pinto",
    "Probe",
    "Ranchero (1967-1970)",
    "Ranchero (1971-1976)",
    "Ranchero (1977 up)",
    "Ranchero (1957-1959)",
    "Ranchero (1960-1966)",
    "Ranger",
    "Taurus",
    "Taurus X",
    "Tempo",
    "ThinkCity-Electric",
    "Thunderbird",
    "Torino",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit Connect",
    "Truck-Courier",
    "Truck-F100",
    "Truck-F150",
    "Truck-F150 Raptor",
    "Truck-F250 not Super Duty (1999 Down)",
    "Truck-F250 Super Duty (1999 Up)",
    "Truck-F350 not Super Duty (1997 Down)",
    "Truck-F350 Super Duty (1999 Up)",
    "Truck-F450 not Super Duty (1997 Down)",
    "Truck-F450 Super Duty (1999 Up)",
    "Truck-F550 Super Duty (1999 Up)",
    "Truck-Forward Control",
    "Truck-Ranger",
    "Van E100",
    "Van E150",
    "Van E200",
    "Van E250",
    "Van E300",
    "Van E350",
    "Van E450 Super Duty",
    "Van E550 Super Duty",
    "Windstar",
    "Other",
  ],
  GMC: [
    "Choose Model",
    "Acadia",
    "Jimmy, Full Size",
    "Jimmy, S10/S15",
    "Safari Van",
    "Sprint",
    "Suburban-10 (1988 Down)",
    "Suburban-20 (1988 Down)",
    "Suburban-30 (1965-1966)",
    "Suburban-1000 (1965-1966)",
    "Suburban-1500 (2001 Down)",
    "Suburban-2500 (1967 Up)",
    "Syclone",
    "Terrain",
    "Truck-1000 Series (1966 Down)",
    "Truck-1500 Series (1999 Down)",
    "Truck-2500 Series (2000 Down)",
    "Truck-3500 Series (2001 Down)",
    "Truck-Canyon",
    "Truck-Envoy",
    "Truck-Envoy XL",
    "Truck-Envoy XUV",
    "Truck-Forward Control",
    "Truck-S10/S15/Sonoma",
    "Truck-Sierra 1500 (1999 Up)",
    "Truck-Sierra 2500 (1999 Up)",
    "Truck-Sierra 3500 (2001 Up)",
    "Truck-Sierra Denali",
    "Truck-Sierra Denali 1500 (2011 Up)",
    "Truck-Sierra Denali 2500 (2011 Up)",
    "Truck-Sierra Denali 3500 (2011 Up)",
    "Truck-Topkick",
    "Truck-Yukon (except XL)",
    "Truck-Yukon XL1500",
    "Truck-Yukon XL2500",
    "Typhoon",
    "Van 1000",
    "Van 1500",
    "Van 2500",
    "Van 3500",
    "Van Savana 1500",
    "Van Savana 2500",
    "Van Savana 3500",
  ],
  Honda: [
    "Choose Model",
    "600",
    "Accord",
    "Acty",
    "Civic",
    "Clarity",
    "Crosstour",
    "CRV",
    "CRX",
    "CRZ",
    "DelSol",
    "Element",
    "FCX",
    "Fit",
    "HRV",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Ridgeline",
    "S2000",
  ],
  Hummer: ["Choose Model", "Hummer", "H1", "H2", "H3"],
  Hyundai: [
    "Choose Model",
    "Accent",
    "Azera",
    "Elantra",
    "Entourage",
    "Equus",
    "Excel",
    "Genesis",
    "Ioniq",
    "Kona",
    "Pony",
    "Santa Fe",
    "Scoupe",
    "Sonata",
    "Stellar",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Veracruz",
    "XG Series",
  ],
  Infiniti: [
    "Choose Model",
    "EX35",
    "EX37",
    "FX",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "J30",
    "JX35",
    "M30",
    "M35",
    "M37",
    "M45",
    "M56",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX4",
    "QX30",
    "QX50",
    "QX56",
    "QX60",
    "QX70",
    "QX80",
  ],
  Isuzu: [
    "Choose Model",
    "Amigo",
    "Ascender",
    "Axiom",
    "Gemini",
    "IMark",
    "Impulse",
    "Oasis",
    "Optima",
    "Reach",
    "Rodeo",
    "Stylus",
    "Trooper/Trooper II",
    "Truck (Big)",
    "Truck-(Mini Pickup)",
    "Truck-(Mini Pickup) Hombre",
    "Truck i280 (Pickup)",
    "Truck i290 (Pickup)",
    "Truck i350 (Pickup)",
    "Truck i370 (Pickup)",
    "Vehicross",
  ],
  Jaguar: [
    "Choose Model",
    "120",
    "140",
    "150",
    "E Pace",
    "F Pace",
    "F Type",
    "Mark 10",
    "S Type",
    "Sedan",
    "Vanden Plas (1997 Down)",
    "Vanden Plas (1998 to 2007)",
    "Vanden Plas (2008 Up)",
    "X Type",
    "XE",
    "XF",
    "XJ Series (2008 Up)",
    "XJR (1993)",
    "XJR (1995 to 1997)",
    "XJR (1998 to 2007)",
    "XJR (2008 Up)",
    "XJS",
    "XJ6",
    "XJ8 (2008 Up)",
    "XJ8 (2007 Down)",
    "XJ12",
    "XK Series (2007 Up)",
    "XKE",
    "XKR (2006 Down)",
    "XKR (2007 Up)",
    "XK8",
  ],
  Jeep: [
    "Choose Model",
    "Cherokee (except Grand Cherokee)",
    "CJSeries",
    "Comanche",
    "Commander",
    "Compass",
    "DJ Series",
    "FC Series",
    "Grand Cherokee",
    "Grand Wagoneer",
    "J-Series",
    "Jeepster",
    "Liberty",
    "Patriot",
    "Renegade",
    "Station Wagon",
    "Truck",
    "Wagoneer (except Grand Wagoneer)",
    "Wrangler",
  ],
  Kia: [
    "Choose Model",
    "Amanti",
    "Besta",
    "Borrego",
    "Cadenza",
    "Forte",
    "K900",
    "Magentis",
    "Niro",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Sephia",
    "Sorento",
    "Soul",
    "Spectra",
    "Sportage",
    "Stinger",
  ],
  Lamborghini: ["Choose Model", "Lamborghini"],
  Landrover: [
    "Choose Model",
    "Defender",
    "Discovery (2004 Down)",
    "Discovery (2017 Up)",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Other",
  ],
  Lexus: [
    "Choose Model",
    "250ES",
    "CT 200H",
    "ES300",
    "ES300H",
    "ES330",
    "ES350",
    "GS200t",
    "GS300",
    "GS350",
    "GS400",
    "GS430",
    "GS450",
    "GS460",
    "GS F",
    "GX460",
    "GX470",
    "HS250H",
    "IS200t",
    "IS250",
    "IS300",
    "IS350",
    "IS F",
    "LC500",
    "LC500h",
    "LFA",
    "LS400",
    "LS430",
    "LS460",
    "LS500",
    "LS500h",
    "LS600HL",
    "LX450",
    "LX470",
    "LX570",
    "NX200t",
    "NX300h",
    "RC 200t",
    "RC 300",
    "RC 350",
    "RC F",
    "RX300",
    "RX330",
    "RX350",
    "RX400 Hybrid",
    "RX450 Hybrid",
    "SC (excl 430)",
    "SC430",
  ],
  Lincoln: [
    "Choose Model",
    "Aviator",
    "Blackwood",
    "Continental",
    "LS",
    "Mark LT",
    "Mark Series",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Navigator",
    "Versailles",
    "Zephyr",
    "Other (includes Town Car)",
  ],
  Maserati: ["Choose Model", "Maserati", "BiTurbo", "Ghibli"],
  Maybach: ["Choose Model", "Maybach"],
  Mazda: [
    "Choose Model",
    "2",
    "3",
    "5",
    "6",
    "323",
    "626",
    "808",
    "929",
    "1200",
    "1800",
    "Cosmo",
    "CX3",
    "CX5",
    "CX7",
    "CX9",
    "GLC",
    "MPV Van",
    "MX3",
    "MX6",
    "Miata MX5",
    "Millenia",
    "Navajo",
    "Pickup-B1600",
    "Pickup-B1800",
    "Pickup-B2000",
    "Pickup-B2200",
    "Pickup-B2300",
    "Pickup-B2500",
    "Pickup-B2600",
    "Pickup-B3000",
    "Pickup-B4000",
    "Pickup-Rotary",
    "Protege",
    "RX2",
    "RX3",
    "RX4",
    "RX7",
    "RX8",
    "Tribute",
  ],
  Mercedes: [
    "Choose Model",
    "170",
    "190",
    "200",
    "218",
    "219",
    "220",
    "230-4 Cyl",
    "230-6 Cyl",
    "240D",
    "250",
    "260E",
    "280",
    "300D (includes CD/D/SD/TD)",
    "300E",
    "300SL",
    "320",
    "350",
    "380",
    "400",
    "420",
    "450",
    "500",
    "560",
    "600",
    "AMG GT",
    "B Class",
    "C Class",
    "CL Class",
    "CLA Class",
    "CLK",
    "CLS",
    "E Class",
    "G Class",
    "GL Class",
    "GLA Class",
    "GLC Class",
    "GLE Class",
    "GLK Class",
    "GLS Class",
    "ML Series",
    "Metris",
    "R Class",
    "S Class",
    "SL Class",
    "SLC Class",
    "SLK",
    "SLR",
    "SLS",
    "Sprinter 2500",
    "Sprinter 3500",
    "Truck",
  ],
  Mercury: [
    "Choose Model",
    "Bobcat",
    "Capri",
    "Comet",
    "Cougar",
    "Grand Marquis (1979 Down)",
    "Grand Marquis (1980 Up)",
    "LN7",
    "Lynx (except LN7)",
    "Marauder",
    "Mariner",
    "Marquis (not Grand)",
    "Merkur (includes XR4TI and Scorpio)",
    "Milan",
    "Monarch",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
    "Zephyr",
    "Other",
  ],
  Mini: [
    "Choose Model",
    "(Austin)",
    "Cooper",
    "Cooper Clubman",
    "Cooper Countryman",
    "Cooper Paceman",
  ],
  Mitsubishi: [
    "Choose Model",
    "3000",
    "Cordia",
    "Diamante",
    "Eclipse",
    "Endeavor",
    "Expo",
    "Fuso",
    "Galant",
    "i MiEV",
    "Lancer",
    "Minicab",
    "Mirage",
    "Montero",
    "Montero-Sport",
    "Outlander",
    "Pickup (See also Dodge D50)",
    "Precis",
    "Raider",
    "RVR",
    "Sigma",
    "Space Wagon",
    "Starion",
    "Tredia",
    "Van",
  ],
  Nissan: [
    "Choose Model",
    "1200",
    "1600",
    "200SX",
    "210",
    "240SX",
    "240Z",
    "260Z",
    "280-Z",
    "280-ZX",
    "300ZX",
    "350Z",
    "370Z",
    "310",
    "311",
    "410",
    "411",
    "510",
    "610",
    "710",
    "810",
    "Almera",
    "Altima",
    "Armada",
    "Axxess",
    "B210",
    "Cube",
    "F10",
    "Frontier",
    "GTR",
    "Juke",
    "Leaf",
    "Lucino",
    "Maxima (1981 Down)",
    "Maxima (1982 Up)",
    "Micra",
    "Murano",
    "NV 200",
    "NV 1500",
    "NV 2500",
    "NV 3500",
    "NX",
    "Pathfinder",
    "Patrol",
    "Platina",
    "Pulsar",
    "Qashqai",
    "Quest",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Stanza (Excl Van)",
    "Stanza Van",
    "Tida",
    "Truck",
    "Truck-Titan",
    "Truck-Titan XD",
    "Tsubame",
    "UD Series",
    "Van GC22",
    "Versa",
    "X Trail",
    "Xterra",
  ],
  Pontiac: [
    "Choose Model",
    "1000",
    "2000-P/J/Sunbird",
    "6000",
    "Acadian",
    "Astre",
    "Aztek",
    "Bonneville (1979 Down)",
    "Bonneville (1980 Up)",
    "Catalina (1979 Down)",
    "Catalina (1980 Up)",
    "Firebird",
    "Firefly",
    "G3",
    "G4",
    "G5",
    "G6",
    "G8",
    "Grand AM",
    "Grand Prix",
    "GTO (New Style)",
    "GTO (Old Style)",
    "Lemans",
    "Matiz",
    "Montana",
    "Parisienne (1979 Down)",
    "Parisienne (1980 Up)",
    "Phoenix",
    "Pursuit",
    "Solstice",
    "Sunbird",
    "Sunburst",
    "Sunfire",
    "Sunrunner",
    "Tempest",
    "Torrent",
    "Trans Sport",
    "Van-Montana",
    "Ventura",
    "Vibe",
    "Wave",
    "Other",
  ],
  Porsche: [
    "Choose Model",
    "356",
    "911/930",
    "912/e",
    "914",
    "918",
    "928",
    "944",
    "968",
    "Boxster",
    "Carrera-GT",
    "Cayenne",
    "Cayman S",
    "Macan",
    "Panamera",
  ],
  RollsRoyce: ["Choose Model", "RollsRoyce"],
  Saab: [
    "Choose Model",
    "9-3 (1999 Up)",
    "9-5 (1999 Up)",
    "92x",
    "93 (1960 Down)",
    "94x",
    "95 (1972 Down)",
    "96",
    "97x",
    "99",
    "900 (incl Turbo)",
    "9000 (incl Turbo)",
    "Monte Carlo",
    "Sonett",
    "Sonett III",
  ],
  Saturn: [
    "Choose Model",
    "Astra",
    "Aura",
    "EV1",
    "Ion",
    "L Series",
    "S Series",
    "Outlook",
    "Relay",
    "Sky",
    "Vue",
  ],
  Subaru: [
    "Choose Model",
    "Baja",
    "Brat",
    "BRZ",
    "Chaser",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Outback (Impreza)",
    "Outback (Legacy)",
    "Sambar",
    "Streega",
    "SVX",
    "Tribeca",
    "WRX (2014 Down)",
    "WRX (2015 Up)",
    "XT",
    "XV Crosstrek",
    "Other",
  ],
  Suzuki: [
    "Choose Model",
    "Aerio",
    "Carry",
    "Esteem",
    "Equator",
    "Forenza",
    "Forsa",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "SJ410",
    "Swift",
    "SX4",
    "Verona",
    "Vitara",
    "X90",
    "XL7",
  ],
  Tesla: ["Choose Model", "Roadster", "S", "X"],
  Toyota: [
    "Choose Model",
    "86",
    "4Runner",
    "Aristo",
    "Avalon",
    "CHR",
    "Camry",
    "Carina",
    "Celica",
    "Corolla iM",
    "Corolla not FX",
    "Corolla FX/FX16",
    "Corona MKII",
    "Corona not MKII",
    "Cressida",
    "Crown",
    "Echo",
    "FJ Cruiser",
    "FX/FX16",
    "HiAce",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Paseo",
    "Previa",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Solara",
    "Starlet",
    "Stout",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Truck (except T100 &amp; Tundra)",
    "Tundra",
    "Van (See also Previa)",
    "Venza",
    "Yaris",
    "Yaris iA",
  ],
  Volkswagen: [
    "Choose Model",
    "412/411",
    "Atlas",
    "Beetle/Bug",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "Dasher",
    "Derby",
    "Eos",
    "Fox",
    "Golf",
    "Golf GTI",
    "Jetta",
    "Jetta GLI",
    "Karmann Ghia",
    "Passat",
    "Phaeton",
    "Pointer",
    "Pointer Truck",
    "Quantum",
    "Rabbit",
    "Routan",
    "Scirocco",
    "Sedan",
    "Sharan",
    "Thing",
    "Tiguan",
    "Touareg",
    "Type 3",
    "Van-EuroVan",
    "Van-Transporter",
    "Van-Vanagon",
    "Other",
  ],
  Volvo: [
    "Choose Model",
    "30 Series",
    "40 Series",
    "50 Series",
    "60 Series",
    "70 Series",
    "80 Series",
    "90 Series",
    "120 Series",
    "140 Series",
    "160 Series",
    "240",
    "260",
    "444/445",
    "544",
    "740",
    "760",
    "780",
    "850",
    "940",
    "960",
    "1800",
    "F7",
    "FE6",
    "S60",
    "S90",
    "Truck",
    "V60",
    "V90",
    "XC60 (2013 Down)",
    "XC60 (2014 Up)",
    "XC70",
    "XC90",
  ],
};

export const TRANSMISSION = [
  "Choose Transmission",
  "2WD / Automatic Tramission",
  "4x4 / Automatic Tramission",
  "2WD / Manual Tramission",
  "4x4 / Manual Tramission",
];

export const PART = [
  "Choose Part",
  "Engine Assembly",
  "Transmission",
  "ABS Control Module",
  "ABS System (Anti-Lock)",
  "AC Compressor",
  "AC Compressor Clutch",
  "AC Condenser",
  "AC Evaporator",
  "Air Bag Control Module",
  "Air Cleaner Box",
  "Air Flow Meter",
  "Air Injection Pump",
  "Alternator",
  "Axle Assembly - Front",
  "Axle Assembly - Rear",
  "Axle Housing",
  "Axle Shaft",
  "Back Glass",
  "Backup Lamp",
  "Beam Axle",
  "Bell Housing",
  "Blower Motor",
  "Body Control Module",
  "Brain Box (Engine)",
  "Brain Box (Not Engine)",
  "Brake Master Cylinder",
  "Bumper Assembly - Front",
  "Bumper Assembly - Rear",
  "Bumper Reinforcement - Front",
  "Bumper Reinforcement - Rear",
  "Camera/Projector",
  "Camshaft",
  "Car Window Lifter",
  "Car Window Regulator",
  "Carburetor",
  "Carrier Assembly",
  "Carrier Case",
  "Clutch Disc",
  "Clutch Master Cylinder",
  "Clutch Slave Cylinder",
  "Coil Spring",
  "Column Switch",
  "Communication Module",
  "Computer (Engine)",
  "Computer (Not Engine)",
  "Condenser Fan",
  "Control Arm - Lower (Front)",
  "Control Arm - Lower (Rear)",
  "Control Arm - Upper (Front)",
  "Control Arm - Upper (Rear)",
  "Convertible Top Lift",
  "Convertible Top Motor",
  "Cooling Fan",
  "Crankshaft",
  "Cruise Switch",
  "Cylinder Block",
  "Cylinder Head",
  "Dash Panel",
  "DC Converter (Inverter)",
  "Decklid",
  "Differential",
  "Differential Assembly",
  "Differential Case",
  "Differential Flange",
  "Distributor Coil",
  "DistributorCoil - Engine",
  "Door Assembly - Front",
  "Door Assembly - Rear",
  "Door Electrical Switch",
  "Door Glass - Front (Side)",
  "Door Glass - Rear (Side)",
  "Door Lock Control Module",
  "Door Vent Glass - Front (Side)",
  "Door Vent Glass - Rear (Side)",
  "Door Window Motor",
  "Door Window Regulator - Front",
  "Door Window Regulator - Rear",
  "Drive Shaft - Front",
  "Drive Shaft - Rear",
  "ECM/ECU (Engine)",
  "ECM/ECU (Not Engine)",
  "ECU (Not Engine)",
  "Electric Door Motor",
  "Electrical Switch (Door)",
  "Electronic Control Module (Engine)",
  "Electronic Control Module (Not Engine)",
  "Engine Coil",
  "Engine Computer",
  "Engine Control Module",
  "Engine Oil Cooler",
  "Exhaust Manifold",
  "Fan Blade",
  "Fan Clutch",
  "Fender",
  "Flywheel",
  "Fog Light Stalk",
  "Front Axle",
  "Front Axle I-Beam (2WD)",
  "Front Body Panel",
  "Front Bumper",
  "Front Bumper Reinforcement",
  "Front Clip",
  "Front Door Assembly",
  "Front Door Glass (Side)",
  "Front Door Hinge",
  "Front Door Vent Glass (Side)",
  "Front End Assembly",
  "Front Fender",
  "Front Side Lamp",
  "Front Spoiler",
  "Front Window Lifter",
  "Front Wiper Motor",
  "Fuel Injection Parts",
  "Fuel Pump",
  "Fuel Pump Control Module",
  "Generator",
  "GPS ScreenTV Info Screen",
  "Grille",
  "Harmonic Balancer",
  "Head Light Assembly",
  "Head Light Door",
  "Head Light Motor",
  "Head Light Switch",
  "Header Panel",
  "Heater Assembly",
  "Heater Core",
  "Heater or Air Conditioner Parts - Misc.",
  "High Mounted Stop Light",
  "Hood",
  "Hood Hinge",
  "Hub Brakes",
  "Ignition Switch",
  "Intake Manifold",
  "Intercooler",
  "Interior Light Control Module",
  "K-Frame",
  "Knee",
  "Leaf Spring - Front",
  "Leaf Spring - Rear",
  "Loaded Beam Axle",
  "Lower Control Arm - Front",
  "Lower Control Arm - Rear",
  "Navigation Control Module",
  "Oil Pan",
  "Overdrive Unit Transmission",
  "Power Brake Boosters",
  "Power Steering Pump",
  "Power Supply Control Module",
  "Power Window Motor",
  "Pressure Plate",
  "Quarter Glass",
  "Quarter Panel",
  "Quarter Window Regulator - Rear",
  "Radiator",
  "Radiator Cooling Fan",
  "Radiator Core Support",
  "Radiator Fan",
  "Radio/Audio Cowl",
  "Rear Axle",
  "Rear Body Panel",
  "Rear Bumper",
  "Rear Bumper Reinforcement",
  "Rear Clip Assembly",
  "Rear Door Assembly",
  "Rear Door Glass (Side)",
  "Rear Door Vent Glass (Side)",
  "Rear Fender",
  "Rear Independent Suspension Assembly",
  "Rear Lower Control Arm",
  "Rear Quarter Panel",
  "Rear Side Lamp",
  "Rear Spoiler",
  "Rear View Mirror",
  "Rear Window Washer Motor",
  "Rear Wiper Motor",
  "Ring Gear and Pinion Assembly",
  "Rocker Arm",
  "Roof Control Module",
  "Roof Glass",
  "SAM Control Module",
  "Seat Control Module",
  "Seat Track - Front",
  "Security System Control Module",
  "Shock Absorber",
  "Side Lamp (Front)",
  "Side Lamp (Rear)",
  "Side View Mirror",
  "Speedometer Cluster",
  "Spindle Knuckle - Front",
  "Spoiler - Front",
  "Spoiler - Rear",
  "Stabilizer Bar",
  "Starter Motor",
  "Starter Solenoid",
  "Steering Column",
  "Steering Gear - Rack & Pinion",
  "Strut",
  "Stub Axle - Rear",
  "Sun RoofMoon Roof",
  "Supercharger",
  "Suspension Compressor/Pump",
  "Suspension Control Module",
  "Suspension Crossmember",
  "Tail Finish Panel",
  "Tail Gate Hinge",
  "Tail Gate Molding",
  "Tail Gate Windor Regulator",
  "Tail Light",
  "Tail Panel",
  "Tailgate",
  "Temperature Control Module",
  "Throttle Body Assembly",
  "Timing Cover",
  "Torque Converter",
  "Torsion Bar",
  "Transfer Case",
  "Transfer Case Assembly",
  "Transmission Control Module",
  "Trunk Lid",
  "Turbocharger",
  "Turn Signal Lever",
  "Upper Control Arm - Front",
  "Upper Control Arm - Rear",
  "Vacuum Pump",
  "Valance - Front",
  "Voltage Regulator",
  "Water Pump",
  "Wheel",
  "Window Lifter",
  "Window Motor",
  "Window Regulator",
  "Window Regulator - Front",
  "Window Regulator - Rear",
  "Window Regulator (Quarter) - Rear",
  "Window Regulator (Tail Gate)",
  "Windshield Washer Motor",
  "Windshield Washer Reservoir",
  "Windshield Wiper Switch",
  "Wiper Motor - Front",
  "Wiper Motor - Rear",
  "Wiper Motor (Windshield)",
  "Wiper Transmission",
];
export const MAKE_ICONS = [
  ["/acura-logo.webp", "Acura"],
  ["/audi-logo.webp", "Audi"],
  ["/bmw-logo.webp", "BMW"],
  ["/buick-logo.webp", "Buick"],
  ["/cadillac-logo.webp", "Cadillac"],
  ["/chevrolet-logo.webp", "Chevrolet"],
  ["/chrysler-logo.webp", "Chrysler"],
  ["/dodge-logo.webp", "Dodge"],
  ["/eagle-logo.webp", "Eagle"],
  ["/ford-logo.webp", "Ford"],
  ["/gmc-logo.webp", "GMC"],
  ["/honda-logo.webp", "Honda"],
  ["/hyundai-logo.webp", "Hyundai"],
  ["/infiniti-logo.webp", "Infiniti"],
  ["/isuzu-logo.webp", "Isuzu"],
  ["/jaguar-logo.webp", "Jaguar"],
  ["/jeep-logo.webp", "Jeep"],
  ["/kia-logo.webp", "Kia"],
  ["/land-rover-logo.webp", "Landrover"],
  ["/lexus-logo.webp", "Lexus"],
  ["/lincoln-logo.webp", "Lincoln"],
  ["/mazda-logo.webp", "Mazda"],
  ["/mercedes-benz-logo.webp", "Mercedes"],
  ["/mercury-logo.webp", "Mercury"],
  ["/mini-logo.webp", "Mini"],
  ["/mitsubishi-logo.webp", "Mitsubishi"],
  ["/nissan-logo.webp", "Nissan"],
  ["/pontiac-logo.webp", "Pontiac"],
  ["/porsche-logo.webp", "Porsche"],
  ["/saab-logo.webp", "Saab"],
  ["/saturn-logo.webp", "Saturn"],
  ["/subaru-logo.webp", "Subaru"],
  ["/suzuki-logo.webp", "Suzuki"],
  ["/toyota-logo.webp", "Toyota"],
  ["/volkswagen-logo.webp", "Volkswagen"],
  ["/volvo-logo.webp", "Volvo"],
];
export const PARTS = [
  "Engine Assembly",
  "Transmission",
  "ABS Control Module",
  "ABS System (Anti-Lock)",
  "AC Compressor",
  "AC Compressor Clutch",
  "AC Condenser",
  "AC Evaporator",
  "Air Bag Control Module",
  "Air Cleaner Box",
  "Air Flow Meter",
  "Air Injection Pump",
  "Alternator",
  "Axle Assembly - Front",
  "Axle Assembly - Rear",
  "Axle Housing",
  "Axle Shaft",
  "Back Glass",
  "Backup Lamp",
  "Beam Axle",
  "Bell Housing",
  "Blower Motor",
  "Body Control Module",
  "Brain Box (Engine)",
  "Brain Box (Not Engine)",
  "Brake Master Cylinder",
  "Bumper Assembly - Front",
  "Bumper Assembly - Rear",
  "Bumper Reinforcement - Front",
  "Bumper Reinforcement - Rear",
  "Camera/Projector",
  "Camshaft",
  "Car Window Lifter",
  "Car Window Regulator",
  "Carburetor",
  "Carrier Assembly",
  "Carrier Case",
  "Clutch Disc",
  "Clutch Master Cylinder",
  "Clutch Slave Cylinder",
  "Coil Spring",
  "Column Switch",
  "Communication Module",
  "Computer (Engine)",
  "Computer (Not Engine)",
  "Condenser Fan",
  "Control Arm - Lower (Front)",
  "Control Arm - Lower (Rear)",
  "Control Arm - Upper (Front)",
  "Control Arm - Upper (Rear)",
  "Convertible Top Lift",
  "Convertible Top Motor",
  "Cooling Fan",
  "Crankshaft",
  "Cruise Switch",
  "Cylinder Block",
  "Cylinder Head",
  "Dash Panel",
  "DC Converter (Inverter)",
  "Decklid",
  "Differential",
  "Differential Assembly",
  "Differential Case",
  "Differential Flange",
  "Distributor Coil",
  "DistributorCoil - Engine",
  "Door Assembly - Front",
  "Door Assembly - Rear",
  "Door Electrical Switch",
  "Door Glass - Front (Side)",
  "Door Glass - Rear (Side)",
  "Door Lock Control Module",
  "Door Vent Glass - Front (Side)",
  "Door Vent Glass - Rear (Side)",
  "Door Window Motor",
  "Door Window Regulator - Front",
  "Door Window Regulator - Rear",
  "Drive Shaft - Front",
  "Drive Shaft - Rear",
  "ECM/ECU (Engine)",
  "ECM/ECU (Not Engine)",
  "ECU (Not Engine)",
  "Electric Door Motor",
  "Electrical Switch (Door)",
  "Electronic Control Module (Engine)",
  "Electronic Control Module (Not Engine)",
  "Engine Coil",
  "Engine Computer",
  "Engine Control Module",
  "Engine Oil Cooler",
  "Exhaust Manifold",
  "Fan Blade",
  "Fan Clutch",
  "Fender",
  "Flywheel",
  "Fog Light Stalk",
  "Front Axle",
  "Front Axle I-Beam (2WD)",
  "Front Body Panel",
  "Front Bumper",
  "Front Bumper Reinforcement",
  "Front Clip",
  "Front Door Assembly",
  "Front Door Glass (Side)",
  "Front Door Hinge",
  "Front Door Vent Glass (Side)",
  "Front End Assembly",
  "Front Fender",
  "Front Side Lamp",
  "Front Spoiler",
  "Front Window Lifter",
  "Front Wiper Motor",
  "Fuel Injection Parts",
  "Fuel Pump",
  "Fuel Pump Control Module",
  "Generator",
  "GPS ScreenTV Info Screen",
  "Grille",
  "Harmonic Balancer",
  "Head Light Assembly",
  "Head Light Door",
  "Head Light Motor",
  "Head Light Switch",
  "Header Panel",
  "Heater Assembly",
  "Heater Core",
  "Heater or Air Conditioner Parts - Misc.",
  "High Mounted Stop Light",
  "Hood",
  "Hood Hinge",
  "Hub Brakes",
  "Ignition Switch",
  "Intake Manifold",
  "Intercooler",
  "Interior Light Control Module",
  "K-Frame",
  "Knee",
  "Leaf Spring - Front",
  "Leaf Spring - Rear",
  "Loaded Beam Axle",
  "Lower Control Arm - Front",
  "Lower Control Arm - Rear",
  "Navigation Control Module",
  "Oil Pan",
  "Overdrive Unit Transmission",
  "Power Brake Boosters",
  "Power Steering Pump",
  "Power Supply Control Module",
  "Power Window Motor",
  "Pressure Plate",
  "Quarter Glass",
  "Quarter Panel",
  "Quarter Window Regulator - Rear",
  "Radiator",
  "Radiator Cooling Fan",
  "Radiator Core Support",
  "Radiator Fan",
  "Radio/Audio Cowl",
  "Rear Axle",
  "Rear Body Panel",
  "Rear Bumper",
  "Rear Bumper Reinforcement",
  "Rear Clip Assembly",
  "Rear Door Assembly",
  "Rear Door Glass (Side)",
  "Rear Door Vent Glass (Side)",
  "Rear Fender",
  "Rear Independent Suspension Assembly",
  "Rear Lower Control Arm",
  "Rear Quarter Panel",
  "Rear Side Lamp",
  "Rear Spoiler",
  "Rear View Mirror",
  "Rear Window Washer Motor",
  "Rear Wiper Motor",
  "Ring Gear and Pinion Assembly",
  "Rocker Arm",
  "Roof Control Module",
  "Roof Glass",
  "SAM Control Module",
  "Seat Control Module",
  "Seat Track - Front",
  "Security System Control Module",
  "Shock Absorber",
  "Side Lamp (Front)",
  "Side Lamp (Rear)",
  "Side View Mirror",
  "Speedometer Cluster",
  "Spindle Knuckle - Front",
  "Spoiler - Front",
  "Spoiler - Rear",
  "Stabilizer Bar",
  "Starter Motor",
  "Starter Solenoid",
  "Steering Column",
  "Steering Gear - Rack & Pinion",
  "Strut",
  "Stub Axle - Rear",
  "Sun RoofMoon Roof",
  "Supercharger",
  "Suspension Compressor/Pump",
  "Suspension Control Module",
  "Suspension Crossmember",
  "Tail Finish Panel",
  "Tail Gate Hinge",
  "Tail Gate Molding",
  "Tail Gate Windor Regulator",
  "Tail Light",
  "Tail Panel",
  "Tailgate",
  "Temperature Control Module",
  "Throttle Body Assembly",
  "Timing Cover",
  "Torque Converter",
  "Torsion Bar",
  "Transfer Case",
  "Transfer Case Assembly",
  "Transmission Control Module",
  "Trunk Lid",
  "Turbocharger",
  "Turn Signal Lever",
  "Upper Control Arm - Front",
  "Upper Control Arm - Rear",
  "Vacuum Pump",
  "Valance - Front",
  "Voltage Regulator",
  "Water Pump",
  "Wheel",
  "Window Lifter",
  "Window Motor",
  "Window Regulator",
  "Window Regulator - Front",
  "Window Regulator - Rear",
  "Window Regulator (Quarter) - Rear",
  "Window Regulator (Tail Gate)",
  "Windshield Washer Motor",
  "Windshield Washer Reservoir",
  "Windshield Wiper Switch",
  "Wiper Motor - Front",
  "Wiper Motor - Rear",
  "Wiper Motor (Windshield)",
  "Wiper Transmission",
];

export const TRANSMISSIONS = [
  "Acura Transmissions",
  "Aston Martin Transmissions",
  "Audi Transmissions",
  "BMW Transmissions",
  "Bentley Transmissions",
  "Buick Transmissions",
  "Cadillac Transmissions",
  "Chevy Transmissions",
  "Chrysler Transmissions",
  "Dodge Transmissions",
  "Ferrari Transmissions",
  "Ford Transmissions",
  "GMC Transmissions",
  "Honda Transmissions",
  "Hummer Transmissions",
  "Hyundai Transmissions",
  "Infiniti Transmissions",
  "Isuzu Transmissions",
  "Jaguar Transmissions",
  "Jeep Transmissions",
  "Kia Transmissions",
  "Lamborghini Transmissions",
  "LandRover Transmissions",
  "Lexus Transmissions",
  "Lincoln Transmissions",
  "Maserati Transmissions",
  "Maybach Transmissions",
  "Mazda Transmissions",
  "Mercedes Transmissions",
  "Mercury Transmissions",
  "Mini Transmissions",
  "Mitsubishi Transmissions",
  "Nissan Transmissions",
  "Pontiac Transmissions",
  "RollsRoyce Transmissions",
  "Saturn Transmissions",
  "Subaru Transmissions",
  "Suzuki Transmissions",
  "Tesla Transmissions",
  "Toyota Transmissions",
  "Volkswagen Transmissions",
  "Volvo Transmissions",
];

export const ENGINES = [
  "Acura Engines",
  "Aston Engines",
  "Audi Engines",
  "BMW Engines",
  "Bentley Engines",
  "Buick Engines",
  "Cadillac Engines",
  "Chevy Engines",
  "Chrysler Engines",
  "Dodge Engines",
  "Ferrari Engines",
  "Ford Engines",
  "GMC Engines",
  "Honda Engines",
  "Hummer Engines",
  "Hyundai Engines",
  "Infiniti Engines",
  "Isuzu Engines",
  "Jaguar Engines",
  "Jeep Engines",
  "Kia Engines",
  "Lamborghini Engines",
  "LandRover Engines",
  "Lexus Engines",
  "Lincoln Engines",
  "Maserati Engines",
  "Maybach Engines",
  "Mazda Engines",
  "Mercedes Engines",
  "Mercury Engines",
  "Mini Engines",
  "Mitsubishi Engines",
  "Nissan Engines",
  "Pontiac Engines",
  "RollsRoyce Engines",
  "Saturn Engines",
  "Subaru Engines",
  "Suzuki Engines",
  "Tesla Engines",
  "Toyota Engines",
  "Volkswagen Engines",
  "Volvo Engines",
];

export const FOOTER = [
  {
    title: "QUICK LINKS",
    content: ["Home", "About Us", "Contact Us", "Search by Make/Model", "Shop Online", "FAQ"]
  },
  {
    title: "RESOURCES",
    content: ["Privacy Policy", "Make a Payment", "Submit a Ticket"]
  },
  {
    title: "CONTACT US",
    content: ["US Toll Free: (877) 982-7774", "Fax: 3124859711", "Email: sales@usedautoparts.pro", "Website: https://usedautoparts.pro"]
  }
]

export const PHONE_NUMBER = "(877) 982-7774";
export const EMAIL_ADDRESS = "sales@usedautoparts.pro";
export const CALL_TO = "tel:8779827774";
export const FAX_ADDR = "3124859711";
